# -*- coding: utf-8 -*-
"""mouse_vision_predator_model.py

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/10cU89ZjWRgm9JL5hm_Zf2llr-1xLLbJ7
"""

# mouse_vision_predator_model.py
# Complete biologically-inspired CNN model for mouse predator detection
# Pipeline: Camera Input → Retina-like preprocessing → Looming Detection → Superior Colliculus Decision → Motor Output (FLEE or FREEZE)
#
# Biological fidelity:
# - Retina: Center-surround (DoG) + OFF-transient response (dark expansion = looming)
# - Upper visual field bias (dorsal retina tuned for overhead aerial predators)
# - Fast threat pathway (~50-80 ms): Retinotectal → Superior Colliculus (SC)
# - Two divergent SC pathways:
#     • Flee: SC PV+ → PBGN → CeA → dPAG → locomotor nuclei (run)
#     • Freeze: SC PV+ → LPTN → lateral amygdala → vlPAG → spinal inhibition (freeze)
# - Slower cortical feedback (V1 layer 5 → SC) for learned safety / suppression of familiar stimuli
#
# this implementation uses pure PyTorch + OpenCV

import torch
import torch.nn as nn
import torch.nn.functional as F
import cv2
import numpy as np
import time
from typing import Dict, Tuple


class RetinaPreprocessor(nn.Module):
    """
    Simulates mouse retinal processing.
    1. Grayscale conversion
    2. Center-surround filtering via Difference of Gaussians (DoG)
    3. OFF-transient response (sensitive to darkening / expanding dark objects)
    """
    def __init__(self):
        super().__init__()
        # Difference of Gaussians kernel (center excitatory, surround inhibitory)
        self.register_buffer('dog_kernel', self._create_dog_kernel())

    def _create_dog_kernel(self, size: int = 11, sigma_center: float = 1.4, sigma_surround: float = 4.2):
        """Create normalized Difference of Gaussians kernel"""
        x = np.linspace(-size//2, size//2, size)
        y = np.linspace(-size//2, size//2, size)
        xx, yy = np.meshgrid(x, y)

        center = np.exp(-(xx**2 + yy**2) / (2 * sigma_center**2))
        surround = np.exp(-(xx**2 + yy**2) / (2 * sigma_surround**2))

        dog = center - 0.85 * surround
        dog = dog / np.max(np.abs(dog))
        return torch.tensor(dog, dtype=torch.float32).unsqueeze(0).unsqueeze(0)

    def forward(self, frame: torch.Tensor) -> Tuple[torch.Tensor, torch.Tensor]:
        """
        Input:  RGB frame (B, 3, H, W) normalized [0,1]
        Output: gray frame, off_response (looming-sensitive)
        """
        # Convert to grayscale
        if frame.shape[1] == 3:
            gray = 0.299 * frame[:, 0:1] + 0.587 * frame[:, 1:2] + 0.114 * frame[:, 2:3]
        else:
            gray = frame

        # Apply center-surround filtering
        padded = F.pad(gray, (5, 5, 5, 5), mode='reflect')
        filtered = F.conv2d(padded, self.dog_kernel, padding=0)

        # OFF-transient response: strong response to darkening (negative contrast)
        off_response = F.relu(-filtered)   # Positive when center becomes darker

        return gray.squeeze(1), off_response.squeeze(1)


class LoomingCNN(nn.Module):
    """
    CNN that mimics OFF-transient α-RGCs and direction/expansion selectivity.
    Detects expanding dark blobs, especially in the upper visual field.
    """
    def __init__(self):
        super().__init__()
        self.conv1 = nn.Conv2d(1, 16, kernel_size=5, stride=2, padding=2)
        self.conv2 = nn.Conv2d(16, 32, kernel_size=3, stride=2, padding=1)
        self.conv3 = nn.Conv2d(32, 64, kernel_size=3, stride=1, padding=1)

        self.pool = nn.AdaptiveAvgPool2d((8, 8))
        self.fc1 = nn.Linear(64 * 8 * 8, 128)
        self.fc2 = nn.Linear(128, 1)   # Looming confidence score

        self.upper_bias = 1.35   # Stronger weight for upper visual field (overhead predators)

    def forward(self, off_response: torch.Tensor) -> torch.Tensor:
        """
        off_response: (B, H, W) from retina
        Returns: looming confidence [0,1]
        """
        x = off_response.unsqueeze(1)  # (B, 1, H, W)

        x = F.relu(self.conv1(x))
        x = F.relu(self.conv2(x))
        x = F.relu(self.conv3(x))

        # Apply upper field bias: multiply upper half by bias factor
        h = x.shape[2]
        upper_mask = torch.ones_like(x)
        upper_mask[:, :, :h//2, :] *= self.upper_bias
        x = x * upper_mask

        x = self.pool(x)
        x = x.view(x.size(0), -1)
        x = F.relu(self.fc1(x))
        looming_score = torch.sigmoid(self.fc2(x))   # probability of looming threat

        return looming_score.squeeze(1)


class SuperiorColliculusDecision(nn.Module):
    """
    Models the SC as a decision hub with two parallel pathways.
    Takes looming features and cortical feedback, outputs FLEE or FREEZE.
    """
    def __init__(self, cortical_feedback_strength: float = 0.82):
        super().__init__()
        self.cortical_feedback_strength = cortical_feedback_strength

        # Two branches representing divergent SC PV+ populations
        self.flee_net = nn.Sequential(
            nn.Linear(5, 64),
            nn.ReLU(),
            nn.Linear(64, 1)
        )

        self.freeze_net = nn.Sequential(
            nn.Linear(5, 64),
            nn.ReLU(),
            nn.Linear(64, 1)
        )

    def forward(self, features: torch.Tensor, cortical_suppression: float = 0.0) -> Dict[str, float]:
        """
        features: [looming_score, expansion_rate, upper_area_ratio, threat_prior, latency_factor]
        cortical_suppression: 0-1 value from V1 feedback (higher = stronger inhibition of fast escape)
        """
        # Apply cortical feedback (learned safety gate)
        suppressed_flee = features.clone()
        suppressed_flee[0] = suppressed_flee[0] * (1.0 - cortical_suppression * self.cortical_feedback_strength)

        flee_score = torch.sigmoid(self.flee_net(suppressed_flee.unsqueeze(0))).item()
        freeze_score = torch.sigmoid(self.freeze_net(features.unsqueeze(0))).item()

        # Decision logic: fast pathway favors FLEE on strong looming, but cortex can override
        if flee_score > freeze_score + 0.15:
            decision = "FLEE"
            confidence = flee_score
            pathway = "SC PV+ → PBGN → CeA → dPAG → brainstem locomotor nuclei (run)"
        else:
            decision = "FREEZE"
            confidence = freeze_score
            pathway = "SC PV+ → LPTN → lateral amygdala → vlPAG → locomotor arrest (freeze)"

        return {
            "decision": decision,
            "confidence": confidence,
            "flee_score": flee_score,
            "freeze_score": freeze_score,
            "pathway": pathway
        }


class MouseVisionPredatorModel:
    """
    End-to-end model: Camera → Retina → Looming CNN → SC Decision → Motor Command
    Motor output is either 'RUN' or 'FREEZE_IN_PLACE' for downstream motor control.
    """
    def __init__(self,
                 sensitivity: float = 0.68,
                 cortical_strength: float = 0.82,
                 device: str = "cpu"):

        self.device = torch.device(device)

        self.retina = RetinaPreprocessor().to(self.device)
        self.looming_cnn = LoomingCNN().to(self.device)
        self.sc_decision = SuperiorColliculusDecision(cortical_feedback_strength=cortical_strength).to(self.device)

        self.sensitivity = sensitivity
        self.prev_gray = None
        self.prev_dark_area = 0

    def extract_features(self, gray: np.ndarray, off_response: np.ndarray) -> Tuple[torch.Tensor, float]:
        """Extract hand-crafted + CNN features for SC input"""
        h, w = gray.shape

        # Compute expansion (temporal difference)
        if self.prev_gray is not None:
            diff = np.maximum(0, self.prev_gray - gray)   # OFF-like temporal change
            dark_area = np.sum(diff > 35)
            expansion_rate = dark_area - self.prev_dark_area
        else:
            dark_area = 0
            expansion_rate = 0

        self.prev_gray = gray.copy()
        self.prev_dark_area = dark_area

        # Upper visual field ratio (overhead = predator likely)
        upper_fraction = np.sum(off_response[:h//2] > off_response.mean() * 1.6) / (h * w / 2 + 1e-6)

        # CNN looming score
        off_tensor = torch.from_numpy(off_response).float().unsqueeze(0).to(self.device)
        with torch.no_grad():
            cnn_score = self.looming_cnn(off_tensor).item()

        # Combine features for SC
        features = torch.tensor([
            cnn_score * self.sensitivity,      # looming_score
            float(expansion_rate) / 100.0,     # normalized expansion
            upper_fraction,                    # upper field activation
            1.0 if cnn_score > 0.45 else 0.0,  # threat prior
            1.0                                # latency bias (fast pathway)
        ], dtype=torch.float32).to(self.device)

        return features, cnn_score

    def process_frame(self, frame: np.ndarray) -> Dict:
        """Full pipeline for one camera frame"""
        start_time = time.time()

        # Preprocess frame
        frame_rgb = cv2.cvtColor(frame, cv2.COLOR_BGR2RGB)
        frame_t = torch.from_numpy(frame_rgb).permute(2, 0, 1).unsqueeze(0).float().to(self.device) / 255.0

        # Retina stage
        gray_t, off_response_t = self.retina(frame_t)
        gray_np = gray_t.squeeze().cpu().numpy()
        off_np = off_response_t.squeeze().cpu().numpy()

        # Looming + feature extraction
        features, cnn_looming = self.extract_features(gray_np, off_np)

        # Simulate cortical feedback (V1 → SC)
        # In a full system this could come from a deeper V1-like network.
        # Here we use a simple heuristic: high texture complexity = possible familiar object → suppression
        texture_complexity = np.std(gray_np) / 60.0
        cortical_suppression = min(0.92, max(0.0, texture_complexity * 0.75))

        # SC decision
        decision_dict = self.sc_decision(features, cortical_suppression)

        latency_ms = (time.time() - start_time) * 1000

        motor_command = "RUN" if decision_dict["decision"] == "FLEE" else "FREEZE_IN_PLACE"

        return {
            "decision": decision_dict["decision"],
            "confidence": decision_dict["confidence"],
            "motor_command": motor_command,
            "pathway": decision_dict["pathway"],
            "looming_cnn_score": cnn_looming,
            "cortical_suppression": cortical_suppression,
            "latency_ms": latency_ms,
            "raw_features": features.cpu().numpy().tolist()
        }

    def run_camera_demo(self, camera_id: int = 0):
        """Real-time webcam demo"""
        cap = cv2.VideoCapture(camera_id)
        cap.set(cv2.CAP_PROP_FRAME_WIDTH, 640)
        cap.set(cv2.CAP_PROP_FRAME_HEIGHT, 480)

        print("Mouse Vision Predator Detection started. Press 'q' to quit.")

        while True:
            ret, frame = cap.read()
            if not ret:
                break

            result = self.process_frame(frame)

            # Visualization
            vis = frame.copy()
            color = (0, 0, 255) if result["decision"] == "FLEE" else (255, 165, 0)

            cv2.putText(vis, f"{result['decision']}  {result['confidence']:.2f}",
                        (30, 60), cv2.FONT_HERSHEY_SIMPLEX, 1.4, color, 4)

            cv2.putText(vis, f"Motor: {result['motor_command']}",
                        (30, 110), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (255, 255, 255), 2)

            cv2.putText(vis, f"Latency: {result['latency_ms']:.1f} ms",
                        (30, 150), cv2.FONT_HERSHEY_SIMPLEX, 0.75, (0, 255, 255), 2)

            if result["decision"] == "FLEE":
                cv2.rectangle(vis, (80, 80), (560, 380), (0, 0, 255), 6)

            cv2.imshow("Mouse Vision - Predator Detection", vis)

            if cv2.waitKey(1) & 0xFF == ord('q'):
                break

        cap.release()
        cv2.destroyAllWindows()


# ====================== Example Usage ======================
if __name__ == "__main__":
    model = MouseVisionPredatorModel(
        sensitivity=0.70,
        cortical_strength=0.82,
        device="cuda" if torch.cuda.is_available() else "cpu"
    )

    # Run live demo with webcam (acts as the "mouse camera")
    model.run_camera_demo()

    # For testing with a static image:
    # frame = cv2.imread("test_image.jpg")
    # result = model.process_frame(frame)
    # print(result)